import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRavelServer } from '../src/api/server.js';

test('HTTP serves UI, historical projection, evidence, focused replay, repair, and SSE', async (t) => {
  const directory = mkdtempSync(join(tmpdir(), 'ravel-api-'));
  const app = await createRavelServer({ directory, demoDelay: 5 });
  await new Promise((resolve) => app.server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${app.server.address().port}`;
  t.after(async () => { await app.close(); rmSync(directory, { recursive: true, force: true }); });
  const get = async (path) => (await fetch(base + path)).json();
  assert.match(await (await fetch(base)).text(), /A race, unraveled/);
  const [run] = await get('/api/runs');
  const state = await get(`/api/runs/${run.run_id}`);
  assert.equal(state.hazards.length, 1);
  const hazard = state.hazards[0];
  assert.equal((await get(`/api/runs/${run.run_id}?seq=1`)).hazards.length, 0);
  const version = await get(`/api/runs/${run.run_id}/version?id=${hazard.observed_version_id}`);
  assert.match(version.content, /INTEGER/);
  const race = await get(`/api/runs/${run.run_id}/race?hazard=${encodeURIComponent(hazard.hazard_id)}`);
  assert.equal(race.length, 5);
  assert.equal((await fetch(`${base}/api/runs/${run.run_id}?seq=-1`)).status, 400);
  assert.equal((await fetch(`${base}/api/runs/nonexistent`)).status, 404);
  assert.equal((await fetch(`${base}/api/demo`, { method: 'POST', headers: { Origin: 'https://example.com' } })).status, 403);
  const repaired = await (await fetch(`${base}/api/runs/${run.run_id}/repair`, { method: 'POST' })).json();
  assert.equal(repaired.active_hazards.length, 0);
  assert.equal(repaired.hazards.length, 1);
  const controller = new AbortController();
  const stream = await fetch(`${base}/api/stream`, { signal: controller.signal });
  assert.equal(stream.headers.get('content-type'), 'text/event-stream');
  const reader = stream.body.getReader();
  await reader.read();
  const started = await (await fetch(`${base}/api/demo`, { method: 'POST' })).json();
  const event = await reader.read();
  assert.match(new TextDecoder().decode(event.value), new RegExp(started.run_id));
  await reader.cancel(); controller.abort();
});
