
CREATE TABLE runs (id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE agents (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), body TEXT NOT NULL);
CREATE TABLE tasks (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), body TEXT NOT NULL);
CREATE TABLE task_attempts (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), body TEXT NOT NULL);
CREATE TABLE events (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), runtime_seq INTEGER NOT NULL, kind TEXT NOT NULL, body TEXT NOT NULL, UNIQUE(run_id, runtime_seq));
CREATE TABLE resources (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), path TEXT NOT NULL, UNIQUE(run_id, path));
CREATE TABLE resource_versions (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), resource_id TEXT NOT NULL, generation INTEGER NOT NULL, body TEXT NOT NULL, UNIQUE(run_id, resource_id, generation));
CREATE TABLE resource_heads (run_id TEXT NOT NULL REFERENCES runs(id), resource_id TEXT NOT NULL, version_id TEXT NOT NULL REFERENCES resource_versions(id), PRIMARY KEY(run_id, resource_id));
CREATE TABLE observations (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), attempt_id TEXT NOT NULL REFERENCES task_attempts(id), version_id TEXT NOT NULL REFERENCES resource_versions(id), body TEXT NOT NULL);
CREATE TABLE attempt_frontier (run_id TEXT NOT NULL REFERENCES runs(id), attempt_id TEXT NOT NULL REFERENCES task_attempts(id), resource_id TEXT NOT NULL, observation_id TEXT NOT NULL REFERENCES observations(id), PRIMARY KEY(attempt_id, resource_id));
CREATE TABLE provenance_edges (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), source_id TEXT NOT NULL REFERENCES resource_versions(id), target_id TEXT NOT NULL REFERENCES resource_versions(id), body TEXT NOT NULL);
CREATE TABLE hazards (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), consumer_id TEXT NOT NULL REFERENCES resource_versions(id), body TEXT NOT NULL);
CREATE TABLE semantic_assessments (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), hazard_id TEXT NOT NULL REFERENCES hazards(id), body TEXT NOT NULL);
CREATE INDEX events_run ON events(run_id, runtime_seq);
CREATE INDEX versions_run ON resource_versions(run_id);
CREATE INDEX hazards_run ON hazards(run_id);
CREATE TRIGGER events_no_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT, 'Events are immutable'); END;
CREATE TRIGGER events_no_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT, 'Events are immutable'); END;
CREATE TRIGGER versions_no_update BEFORE UPDATE ON resource_versions BEGIN SELECT RAISE(ABORT, 'Versions are immutable'); END;
CREATE TRIGGER versions_no_delete BEFORE DELETE ON resource_versions BEGIN SELECT RAISE(ABORT, 'Versions are immutable'); END;
