// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from 'spacetimedb';

// Import all reducer arg schemas
import PublishSnapshotReducer from '../publish_snapshot_reducer';

export type PublishSnapshotParams = __Infer<typeof PublishSnapshotReducer>;
