// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export const BlastRadius = __t.object('BlastRadius', {
  id: __t.string(),
  runId: __t.string(),
  runtimeSeq: __t.u32(),
  summaryJson: __t.string(),
});
export type BlastRadius = __Infer<typeof BlastRadius>;

export const DebuggerAgent = __t.object('DebuggerAgent', {
  id: __t.string(),
  runId: __t.string(),
  runtimeSeq: __t.u32(),
  summaryJson: __t.string(),
});
export type DebuggerAgent = __Infer<typeof DebuggerAgent>;

export const DebuggerRun = __t.object('DebuggerRun', {
  runId: __t.string(),
  runtimeSeq: __t.u32(),
  snapshotJson: __t.string(),
});
export type DebuggerRun = __Infer<typeof DebuggerRun>;

export const Hazard = __t.object('Hazard', {
  id: __t.string(),
  runId: __t.string(),
  runtimeSeq: __t.u32(),
  summaryJson: __t.string(),
});
export type Hazard = __Infer<typeof Hazard>;

export const Publisher = __t.object('Publisher', {
  id: __t.u32(),
  identity: __t.identity(),
});
export type Publisher = __Infer<typeof Publisher>;

export const ResourceVersion = __t.object('ResourceVersion', {
  id: __t.string(),
  runId: __t.string(),
  runtimeSeq: __t.u32(),
  summaryJson: __t.string(),
});
export type ResourceVersion = __Infer<typeof ResourceVersion>;

export const SemanticAssessment = __t.object('SemanticAssessment', {
  id: __t.string(),
  runId: __t.string(),
  runtimeSeq: __t.u32(),
  summaryJson: __t.string(),
});
export type SemanticAssessment = __Infer<typeof SemanticAssessment>;

export const TimelineEvent = __t.object('TimelineEvent', {
  id: __t.string(),
  runId: __t.string(),
  runtimeSeq: __t.u32(),
  summaryJson: __t.string(),
});
export type TimelineEvent = __Infer<typeof TimelineEvent>;
